const Product=[
    {
        id:1,
        name:"samsung s21",
        description:"black-in-color",
        price:"40000",
        imgsrc:"/images/images-1.jpg",
        quantity:1
    },
    {
        id:2,
        name:"samsung galaxy",
        description:"black-in-color",
        price:"40000",
        imgsrc:"/images/image-1.jpg",
        quantity:1
    },
    {
        id:3,
        name:"I-phone",
        description:"black-in-color",
        price:"100000",
        imgsrc:"/images/iphone.jpg",
        quantity:1
    },
    {
        id:4,
        name:"Nokia",
        description:"black-in-color",
        price:"2000",
        imgsrc:"/images/nokia.jpg",
        quantity:1
    },
    {
        id:5,
        name:"Redmi",
        description:"black-in-color",
        price:"25000",
        imgsrc:"/images/redmi.jpg",
        quantity:1
    },
    {
        id:6,
        name:"Sony",
        description:"black-in-color",
        price:"89000",
        imgsrc:"/images/sony.jpg",
        quantity:1
    },
    {
        id:7,
        name:"VIVO",
        description:"black-in-color",
        price:"22000",
        imgsrc:"./images/vivo.jpg",
        quantity:1
    }
]
export default Product;